### ISSUE TITLE
Topbar Button stuck in loading state on Spotify launch

### ISSUE THREAD

**Issue by adufr** [adufr/spicetify-quick-add-to-playlist#1]
The topbar icon randomly stays in its initial loading state on launch
Workaround is to close Spotify and reopen it until it displays the correct state

**Comment by adufr** [comment]
I don't really know whats causing the issue, I just tried increasing the startup timeout (in v1.0.2)
I will see if this fixes it...

**Comment by darkvoilet** [comment]
I have the same issue. Still didn't find a way to fix?

**Comment by adufr** [comment]
No, I haven't been able to figure out what happens because I can't really reproduce it, its very random/rare...
When it happens, the workaround is just to close Spotify and start it again 😞
