### ISSUE TITLE
Box around selected playlist

### ISSUE THREAD

**Issue by orangejuice5519** [adufr/spicetify-quick-add-to-playlist#20]
Hi, I'm having a problem with the extension used with themes. There seems to be a black box around my selected playlist. (Love the extension, thank you!!)
![Screenshot 2023-12-03 at 2 41 11 PM](https://github.com/adufr/spicetify-quick-add-to-playlist/assets/12074053/fd0986ea-39ac-4e60-be3c-3f261a228410)

**Comment by adufr** [comment]
Hello @orangejuice5519! This is actually a feature, I've put this background to have a quick visual feedback of which playlist is the currently selected playlist

You can customize this "box"'s color to better match your theme by going to your Spotify settings (by clicking on your Avatar), scrolling to the bottom where you can find the following section:
<img width="889" alt="image" src="https://github.com/adufr/spicetify-quick-add-to-playlist/assets/26418696/5e23a9f4-90a9-4978-a4df-a512098f834c">
Don't forget to click the little "Apply" button on the bottom right once you've made your changes!

**Comment by orangejuice5519** [comment]
Oh, thank you so much for clarifying!!
