### ISSUE TITLE
Request for Compliance with GNU GPL and Attribution for Code Usage

### ISSUE THREAD

**Issue by ohitstom** [adufr/spicetify-quick-add-to-playlist#44]
Firstly, I would like to clarify that the code you've adapted appears to be derived from my original work, which is licensed under the GNU General Public License (GPL) Version 3. As such, any modifications or distributions made to the code are subject to the terms of this license.

Upon reviewing your repository, I noticed that there is no explicit mention of the GPL or any other license, and the modifications made to the code are not attributed to the original source in a meaningful way. This raises concerns regarding compliance with the GPL and proper attribution of authorship.

As the original author of the code, I kindly request that you take the following actions to ensure compliance and uphold the principles of open source software:

1. Add a License: Please add the appropriate open source license to your repository, GNU GPL Version 3, to clarify the rights and obligations of users and contributors - this is a requirement when distributing (or modifying and distributing) GPL licensed code.

2. Provide Attribution: It's essential to acknowledge the origin of the code by providing proper attribution to the original author, including a mention of my name and a link to the original repository in your readme, whilst i appreciate that you added a single line at the top of the main tsx file - i believe this isnt enough under the license and i hope you can understand why i would want the end user to see where the code has come from, this extends to adding my name to the marketplace manifest for this particular extension.

3. Ensure Compliance: Please ensure that any distributions of the modified code are made under the same GPL license terms, including the inclusion of the GPL license text and the provision of source code to recipients.

It would also be super if you could add in the readme what you have actually changed as other than the obvious tsx conversion there doesnt seem to be a whole lot of actual change.

**Comment by adufr** [comment]
Hi! Thanks for reaching out; I'll make sure to add a license ASAP, it wasn't my intention to claim your code as being mine (as a proof a good faith, you can already see that [I mentioned your repository in the code](https://github.com/adufr/spicetify-extensions/blob/c9a58d26b0bf8ba26ada1c956de4eda77dc7242d/quick-add-to-queue/src/app.tsx#L1))

As for why I copied it; I was planning on tweaking it by adding some features, but tbh I just haven't had the time to do it yet 😬

Sorry for that, again I'll make sure to add a license in the upcoming week! Cheers

**Comment by ohitstom** [comment]
> Hi! Thanks for reaching out; I'll make sure to add a license ASAP, it wasn't my intention to claim your code as being mine (as a proof a good faith, you can already see that [I mentioned your repository in the code](https://github.com/adufr/spicetify-extensions/blob/c9a58d26b0bf8ba26ada1c956de4eda77dc7242d/quick-add-to-queue/src/app.tsx#L1))
> 
> As for why I copied it; I was planning on tweaking it by adding some features, but tbh I just haven't had the time to do it yet 😬
> 
> Sorry for that, again I'll make sure to add a license in the upcoming week! Cheers

awesome, any chance you could stick my name somewhere in the readme and marketplace manifest too? would appreciate it if possible - license is the main thing though lol!

**Comment by adufr** [comment]
yup of course

**Comment by adufr** [comment]
Done ✅ 

On a side note, I read [your license](https://github.com/ohitstom/spicetify-extensions/blob/main/LICENSE) and it looks like you need to add your name at the end of it
