### ISSUE TITLE
You alive??

### ISSUE THREAD

**Issue by RetardedNConfused** [adufr/spicetify-quick-add-to-playlist#6]
would love an option to have several options. it kind of worked before with having both manual installed [quick-add-to-playlist.js] and the marketplace one but that doesnt seem to work anymore. It would be neat if there could also be some way to distinguish the two.

**Comment by adufr** [comment]
Hi! (Sorry I recently broke my elbow and couldn't use my computer anymore)
I just tried to clean install everything (latest spotify, spicetify, marketplace and quick-add-to-playlist), and everything seems to be working just fine!

Btw the marketplace is just an easier way to install extensions, but the extension itself is the very same if you install it yourself or with the help of the marketplace.
Anyway, I recommend to only use it from marketplace ;)
